name: clang-doc

on:
  push:
    branches: [main]

jobs:
  docs:
    name: Generate documentation with clang-doc
    if: github.repository == 'chromium/subspace'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.DOCS_SSH_PRIVATE_KEY }}

      - name: Install LLVM+Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16 all

      - name: Checkout depot tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Setup .gclient
        shell: bash
        run: |
          echo "./depot_tools" >> $GITHUB_PATH
          cp tools/standalone.gclient .gclient

      - name: Download dependencies
        shell: bash
        run: gclient sync --jobs=16

      - name: Configure
        run: |
          # Path to LLVM+Clang nightly that we have installed.
          export LLVM_DIR="/usr/lib/llvm-16/lib/cmake/llvm"
          export Clang_DIR="/usr/lib/llvm-16/lib/cmake/clang"

          sudo apt install build-essential cmake ninja-build
          # Skip building documentation for Cir, which ends up building docs for all of
          # Clang and LLVM too.
          cmake -G Ninja -B out -D CMAKE_EXPORT_COMPILE_COMMANDS=1 -D SUBSPACE_BUILD_CIR=OFF

      - name: Checkout docs
        run: |
          git clone git@github.com:danakj/subspace-docs.git docs

      - name: Generate
        run: |
          # Work around https://github.com/llvm/llvm-project/issues/59815 as the
          # default stylesheet and index.js are not included in the debian
          # package, which leads to an error when running the tool.
          sudo mkdir -p /usr/lib/llvm-16/share/clang/
          sudo cp tools/clang-doc/clang-doc-default-stylesheet.css /usr/lib/llvm-16/share/clang/
          sudo cp tools/clang-doc/index.js /usr/lib/llvm-16/share/clang/

          clang-doc-16 \
            --executor=all-TUs \
            --format=html \
            --public \
            --extra-arg=-Wno-error \
            --project-name=Subspace \
            --repository=https://github.com/chromium/subspace/blob/main \
            --output=docs \
            -p out compile_commands.json

      - name: Deploy
        run: |
          SHA=`git rev-parse HEAD`
          cd docs
          git config user.email "noreply@chromium.org"
          git config user.name "Subspace clang-doc generator"
          git add .
          git commit -m "Update docs: $SHA"
          git push origin

