name: subdoc

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.txt"
      - ".vscode/**"

jobs:
  docs:
    name: Generate Subdoc
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install LLVM+Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16 all

      - name: Install Python3
        run: |
          sudo apt-get install python3

      - name: Download Ninja
        id: ninja
        shell: cmake -P {0}
        run: |
          set(ninja_version "1.11.1")

          set(ninja_url "https://github.com/ninja-build/ninja/releases/download/v${ninja_version}/ninja-linux.zip")
          file(DOWNLOAD "${ninja_url}" ./ninja.zip SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ninja.zip)

          if (NOT "${{ runner.os }}" STREQUAL "Windows")
            execute_process(
              COMMAND chmod +x ninja
            )
          endif()

      - name: Checkout depot tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Setup .gclient
        shell: bash
        run: |
          echo "./depot_tools" >> $GITHUB_PATH

      - name: Download dependencies
        shell: bash
        run: |
          gclient sync --jobs=16

      - name: Configure
        shell: cmake -P {0}
        run: |
          set(ENV{CC} clang-16)
          set(ENV{CXX} clang++-16)

          # Path to LLVM+Clang nightly that we have installed.
          set(ENV{LLVM_DIR} "/usr/lib/llvm-16/lib/cmake/llvm")
          set(ENV{Clang_DIR} "/usr/lib/llvm-16/lib/cmake/clang")

          file(TO_CMAKE_PATH "$ENV{GITHUB_WORKSPACE}/ninja" ninja_program)

          execute_process(
            COMMAND cmake
              -S .
              -B out
              -D CMAKE_BUILD_TYPE=Release
              -D CMAKE_EXPORT_COMPILE_COMMANDS=1
              -G Ninja
              -D CMAKE_MAKE_PROGRAM=${ninja_program}
              -D SUBSPACE_BUILD_TESTS=OFF
              -D SUBSPACE_BUILD_CIR=OFF
              -D SUBSPACE_BUILD_SUBDOC=ON
            RESULT_VARIABLE result
          )
          if (NOT result EQUAL 0)
            message(FATAL_ERROR "Bad exit status")
          endif()

      - name: Build
        shell: cmake -P {0}
        run: |
          set(ENV{NINJA_STATUS} "[%f/%t %o/sec] ")

          execute_process(
            COMMAND cmake --build out
            RESULT_VARIABLE result
          )
          if (NOT result EQUAL 0)
            message(FATAL_ERROR "Bad exit status")
          endif()

        # Generate for files in subspace. We execute the tool on all files in
        # the subspace library dir, and we limit generation to things defined
        # in that directory (there's no other /subspace/ directory it may include).
      - name: Generate
        run: |
          # For crash dumps.
          export LLVM_SYMBOLIZER_PATH="/usr/lib/llvm-16/bin/llvm-symbolizer"

          out/subdoc/subdoc \
            -p out \
            --out docs \
            --include-file-pattern /subspace/ \
            --exclude-file-pattern /third_party/ \
            --copy-file subdoc/gen_tests/subdoc-test-style.css \
            --css subdoc-test-style.css \
            --copy-file subspace/index.html \
            /home/runner/work/subspace/subspace/subspace
